### ISSUE TITLE
Expanded inventory + Infinite Quest bag

### ISSUE THREAD

**Issue by alerum68** [ZaneDubya/MedievaLandsPublic#350]
A new item or items that will expand storage space.  Will take up 1 item slot but will provide at least 6 new storage spots.

**Comment by ZaneDubya** [comment]
This is an interesting idea. I'm filing it in future features because it would require refactoring the item collection code - and that's brittle enough as it is! (Partying and Item collections are two areas of the codebase that definitely deserve signs that say "here there be dragons" and "abandon hope all ye who enter here").

**Comment by ZaneDubya** [comment]
I've had more than a few requests for an expanded inventory. If I were to do this, I would set the total inventory space to some value more than 10 (say 15, 18, or 20), and make the quest bag hold an infinite number of items that could never be moved out of the quest bag.

**Comment by alerum68** [comment]
Maybe allow only what items in the quest bad to ensure that someone doesn't put a weapon they need in there. There is also the flex sword which is a usable weapon and a quest item... There might be others.

**Comment by ZaneDubya** [comment]
Not able to do this, but will be adding some additional space in the keep.
