### ISSUE TITLE
UI: show debuffs / buffs on enemies (Azamath)

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/MedievaLandsPublic#642]

**Comment by HeofHIShirts** [comment]
Yes, please, for both Yserbius and Twinion! The game mechanics have changed significantly since I was playing the original. Spells like Control, Petrify, and Backfire no longer work in the same way that they did during the original games, where once their status was successfully applied to enemies, it didn't wear off until the combat was finished or the enemies under that status were killed.

This made the Cloewyn's Ghost fight in MedievaLands Yserbius significantly harder than it was in the original for a solo player, and has made the Lord Aqueus fight in MedievaLands Twinion nearly impossible for a player to finish at the first point where they might encounter it, because as soon as Aqueus is not petrified, he tends to one-shot a solo player. If the player is expected to continue to re-cast Petrify or any other spells that invoke status effects, having a notice in the text box and/or the enemy portraits as to when those statuses wear off so the player can plan and re-cast accordingly, rather than having to wonder whether their next attack with be countered with their immediate doom would be very helpful. In a perfect world, it would be possible to know how many turns of status effect are left (if that is a fixed value) and things like how much poison damage is being done to enemies in the same way that the player's portrait shows buffs and debuffs applied to them when it is clicked upon, if not on the enemy icons themselves.

**Comment by ZaneDubya** [comment]
Hey Alex! Thanks for weighing in here as well. You are absolutely right - in the original Yserbius, spells like Control did not wear off. That's a change from the original game.

You're also right here in that this change does require more information to be telegraphed to the player. I'll get to work on that. :)

**Comment by ZaneDubya** [comment]
Working on this...

**Comment by ZaneDubya** [comment]
Client now receives buff information for monsters. No interface yet for displaying the same. Working on it...

**Comment by ZaneDubya** [comment]
In test

**Comment by ZaneDubya** [comment]
Complete, ready to deploy to production.
