### ISSUE TITLE
[Suggestion] Spell scaling for magic based classes | Yserbius

### ISSUE THREAD

**Issue by 8byteGaming** [ZaneDubya/MedievaLandsPublic#742]
This would be a suggestion to change the "vanilla" core of the game to fix a balance issue inherent to it. Magic damage does not scale; nor does it reward class\race choices mid-late game.

1.) Eventually you have enough mana to cast to spells that always do the same max damage regardless of class\race. To make casters and caster races relevant you would have to base mana cost and spell damage on the max mana pool.

2.) Some spells are irrelevant late game. Spells like lightning are not useful when you have blast and fireball when you have a large mana pool. You could "morph" low level spells to gain an additional feature at X % max mana pool or character level. Lightning could have a change to affect a group or multiple groups at higher levels as one example.

3.) Passive skills do not include mana regen. % change to regen mana or use reverie(without penalty) on cast of other spells might be useful.

4.) Mana potions and reverie are capped at static variable amounts instead of % based.

5.) Some of the ideas could be added to armor instead of skills or character development.

6.) Spells never crit

Some of these changes might help with the core game loop and add some variety.

Let me know if I can help in any way, thanks. Matt Hingst - 8byteGaming

**Comment by ZaneDubya** [comment]
Hey @8byteGaming ! I am very sorry I have not yet responded to this issue you opened. This pandemic has put me in a strange head space, and it has been hard to focus on anything. That said, I have been back at this project for the past four weeks and hope recent past will be precedent for the near future.

These are good ideas. Thanks for adding them to this ongoing conversation of what a slightly modernized version of Yserbius might look like.

I think that instead of changing the mechanics of the original game, I am more inclined to tinker around the edges (like adding critical hits for spells, instead of changing the mechanics of the spells themselves) at this time. I consider 'around the edges' to include adding new items - even items that add statistics that do not exist in the original game. This will allow characters to specialize - mages will choose +mana and +magic damage items, whereas more physical classes will pick +hp, +armor, +damage items. By making Yserbius a more item-based game, I think I can add a lot of breadth without meddling overmuch with the original game's data. With this in mind, I think you will see some of these ideas added to the game in the near future as items. 

Keep in touch. :)
